- README.md
This PR fixes a small typo I made in #2 in the codecov URL of the README
> docs: Fixed README URL

- CONTRIBUTING.md
Added instructions to run unit tests and lint verification.
> docs: Updated Contributing docs

- .github/workflows/main.yml
This PR simply updates the cache manager action version and renames some variables that were referring to a python package, while the project is not a package currently.
> chore: Updated CI cache manager version

- src/app/api/routes/devices.py
- src/app/api/routing.py
- src/app/api/schemas.py
This PR refactors slightly the schemas to better leverage class inheritance.
> refactor: Refactored schemas 

- requirements.txt
Micro PR: setting q minimum version for some packages using my own personal requirements.
> add min requirements

- src/app/api/routes/accesses.py
- src/app/api/routes/devices.py
- src/app/api/routes/users.py
- src/app/api/schemas.py
- src/app/db/tables.py
- src/tests/conftest.py
- src/tests/test_devices.py
- src/tests/test_users.py
This PR renames the string identifiers of the users and devices tables as per #30
> refactor: Renamed users.username and devices.name fields

- src/app/api/routes/events.py
- src/app/api/routes/media.py
- src/app/api/routes/sites.py
This PR aims at adding summary and description to the events routes.
> [docs][events] Add summary and description to events routes

- src/app/config.py
This PR aims at raising an error if Credentials are missing from environment variables.
Now, it raises an ValueError if SUPERUSER_PWD/SUPERUSER_LOGIN is None.
It will improve debugging.
> [init][config][bug] Add a warning/error to verify that DB is not init with None credentials

- src/app/api/routes/login.py
This PR aims at adding description to the login route.
I am hesitating, adding in the description, something like "This API follows the OAuth 2.0 specification.
Depending on the scope of the access related to credentials, the token expires at a given time"
What do you think ? 
> [doc][login] Add description to login route

- src/app/api/routes/installations.py
Since the device listing route is a reading route, I switched it from POST method to GET.
> fix: Fixed route type on installations/site-devices

- src/app/api/routes/devices.py
- src/app/api/schemas.py
- src/tests/test_devices.py
As per #79, normal users were not able to register their own devices.
This PR fixes that and will close #79
> feat: Added a route for a user to register her/his own device

- src/app/api/routes/sites.py
In the issue #45 we decide to define scopes for all routes in order to protect the API
This PR aims at adding scopes for sites route.
However, should we add the right to any auth user to CU sites ? What do you think ?
(I would add "me" in scopes in this case)
> [scopes][sites]Add admin scopes to CUD routes

- src/app/api/routes/events.py
In the issue #45 we decide to define scopes for all routes in order to protect the API.
This PR aims at adding scopes for events routes.
> [scopes][events] Add scopes to CUD routes

- client/README.md
- client/pyroclient/client.py
- client/pyroclient/exceptions.py
- src/app/api/routes/alerts.py
Add missing client routes mentionned in #75 .
Tested on the local API.
closes #75 
NB: the media is not yet uploaded as we don't have included the Qarnot computing bucket service.
> Add missing client routes

- .gitignore
- client/pyroclient/client.py
- added arguments and return details in the docstrings of the client methods
- added usage examples for each client method
Successfully merging this PR will close #110
> docs: Added detailed examples in client documentation

- client/pyroclient/client.py
- client/test/test_client.py
- src/app/api/crud/base.py
- src/app/api/routes/events.py
- src/tests/routes/test_events.py
- added exclusion criteria option in fetch_all
- added route to fetch past events
- added corresponding unittest
- added API client integration
- added client unittest
Successfully merging this PR will close #109
Any feedback is welcome
> feat: Added route to fetch past fires

- src/app/api/routes/devices.py
Following up on #45, this PR introduces the following modifications:
- added admin scope to device update route
> feat: Added admin scopes to device routes

- src/app/api/routes/installations.py
Following up on #45, this PR introduces the following modifications:
- added admin scope to installation GET routes
> feat: Added admin scopes to installation routes

- client/pyroclient/client.py
Following the merge of #130 , add a function in client to query the newly added route.
> [Client][Site] add no alert site in client

- scripts/api_e2e.py
Following up on #134, this PR introduces the following modifications:
- fixes the payload for the device entry
- added proper DB cleanup at the end of the script
> fix: Fixed end-to-end script

- src/app/api/crud/__init__.py
- src/app/api/crud/webhooks.py
- src/app/api/external.py
- src/app/api/routes/alerts.py
- src/app/api/routes/webhooks.py
- src/app/api/schemas.py
- src/app/db/tables.py
- src/app/main.py
- src/tests/test_external.py
Following up on #145, this PR introduces the following modifications:
- adds a `webhooks` table with the fields `id`, `callback` and `url`
- using the above, added an alert_notification background task upon alert creation
- added corresponding unittests
Resolves #145
> feat: Added webhook system and alert notifications to third-parties

- .github/workflows/docker-publish.yaml
This PR adds a workflow to publish the docker to DockerHub upon each release.
> chore: Added a job to push docker to DockerHub

- client/pyroclient/client.py
- src/app/main.py
This PR simply fixes the docstring examples from the API client
> docs: Fixed client docstring examples

- src/app/main.py
This PR simply adds a console log message when Sentry is enabled and correctly set up
> feat: Added console log to notify that Sentry is enabled

- client/mypy.ini
- client/pyroclient/client.py
- client/test/test_client.py
This introduces the following modifications:
- reordered the dictionary for route mapping
- extended client unittests
> test: Extended client unittests

- client/pyroclient/client.py
- client/test/test_client.py
- added token refresh method to API client
- added unittest
> feat: Added token refresh method to client

- .github/workflows/docs.yml
This PR fixes the deployment job of the documentation for the client
> chore: Fixed client documentation deployment job

- client/pyproject.toml
This PR fixes a typo in the client pyproject.toml
> fix: Fixed client package name

- client/pyproject.toml
This PR fixes the author entry in the pyproject.toml of the client.
> docs: Fixed author entry in pyproject

- README.md
- client/README.md
- client/docs/source/conf.py
- client/pyroclient/client.py
- fixes the doc badges on READMEs
- fixes the rendering of docstring examples for the client
> docs: Fixes README badge and client documentation

- .github/workflows/release.yml
- README.md
- client/.conda/meta.yaml
- client/README.md
- client/docs/source/changelog.rst
- client/pyproject.toml
- client/setup.py
- src/app/config.py
- updates the README badges
- updates the version index
- updates the CI release job
- fixes the conda recipe for pyroclient
- updates the changelog in the documentation
- added upper bound for `requests` in pyroclient
> chore: Applied post release modifications

- README.md
Fix link to contributing section
> docs: Fixes the hyperlink to CONTRIBUTING in the README

- CONTRIBUTING.md
- client/CONTRIBUTING.md
- client/Makefile
- client/README.md
- client/docs/source/installing.rst
This PR improves the README of the client to add detailed explanation about how to use it.
> docs: Revamped client README

- README.md
This PR fixes a typo in the SENTRY_DSN example of the README.
> docs: Fixed Sentry DSN example

- README.md
This PR adds a database UML of the PostgreSQL local DB.
I exported the empty database, then imported it into https://dbdiagram.io/d to produce the UML.
> docs: Added table UML in the README

- README.md
fix link to CONTRIBUTING in README.md
> docs: fix link to CONTRIBUTING

- .github/workflows/pr-labels.yml
Fix link to verify_labels.py in pr-labels.yml
> docs: link to verify_labels in pr-labels workflow

- client/pyroclient/client.py
- client/tests/test_client.py
This PR adds timeout to the python client as well as a test case.
Closes #249
> feat: Adds timeout to Python client requests

- .github/workflows/style.yml
- poetry.lock
- pyproject.toml
- src/app/api/crud/authorizations.py
- src/app/api/endpoints/devices.py
- src/app/api/external.py
- src/app/config.py
- src/app/models/access.py
- src/app/models/alert.py
- src/app/models/device.py
- src/app/models/event.py
- src/app/models/group.py
- src/app/models/installation.py
- src/app/models/media.py
- src/app/models/site.py
- src/app/models/user.py
- src/app/schemas/base.py
- src/app/schemas/devices.py
- src/app/schemas/events.py
- src/app/schemas/installations.py
- src/app/schemas/sites.py
- src/tests/test_schemas.py
- src/tests/utils.py
This PR fixes pydantic validators and code quality to pass mypy checks.
- dependencies added: python-dotenv to facilitate dev experience ; library stubs in quality group (optional)
- mypy config: use pydantic.mypy plugin
> fix: pydantic validators and code quality

- src/Dockerfile-dev
- src/tests/routes/test_alerts.py
- test alert grouping within ALERT_RELAXATION_SECONDS (+ tolerance)
- fix image path in Dockerfile-dev
> test: explicitly test alert grouping (#280)

- .github/workflows/builds.yml
- .github/workflows/docs.yml
- .github/workflows/publish.yml
- .github/workflows/push.yml
- client/.conda/meta.yaml
- pyproject.toml
- adds a docker build + push on "latest" tag on each commit (vs. each release before)
- adds additional build jobs for the client to spot problems with some OS or python versions
- fixes pypi & conda jobs for release
> ci: Adds autopush to dockerhub on commit

- .github/workflows/push.yml
This PR adds an auto-deploy mechanism using the Docker image that has been pulled from the hub.
PS: this shouldn't be deployed before the migrations are finished
> ci: Adds CI job to deploy to dev server

- src/app/crud/base.py
- src/app/db.py
This PR fixes the recent mypy warnings by removing legacy ignore & adding the recent ones (hopefully to all be removed later)
> style(src): fix type annotations

- .github/labeler.yml
- CONTRIBUTING.md
- scripts/dbdiagram.txt
Following up on #332, this PR updates the UML of the database & the PR labeler.
> docs(uml): add organization to DB UML

- .github/workflows/tests.yml
- CONTRIBUTING.md
- Makefile
- docker-compose.test.yml
- scripts/localstack/setup-s3.sh
- src/app/api/endpoints/events.py
- src/app/schemas/events.py
- src/tests/routes/test_events.py
- src/tests/test_services.py
=> Send back media_url with Events in order to be more efficient in the platform side
> Old datamodel : add url into fetch_unacknowledged events

- CONTRIBUTING.md
- scripts/dbdiagram.txt
This PR simply updates the UML of the database by adding the bboxes introduced in #340
> docs(contributing): update the DB UML

- .github/workflows/push.yml
This PR removes the step that kills containers by force.
> ci(push): fix continuous deployment

- src/app/core/config.py
This PR make the value of support email optional.
close #384
> fix(config): make support email optional

- CONTRIBUTING.md
This PR adds some missing information about the tables and migration.
Close #216
Close #275
> docs(contributing): update table description and workflow

- .pre-commit-config.yaml
- src/app/api/api_v1/endpoints/cameras.py
- src/app/crud/crud_camera.py
- src/app/schemas/cameras.py
- src/tests/endpoints/test_cameras.py
This PR:
- adds PATCH `cameras/{cam_id}/name` endpoint to edit the name of a camera
- adds corresponding tests
- update precommit configs
> feat(cameras): add PATCH route to edit name value

- src/app/api/api_v1/endpoints/cameras.py
- src/tests/endpoints/test_cameras.py
This PR:
- add "last_image_url" in the response payload of `GET /api/v1/cameras/{camera_id}`, where, if there is a last image, it will include the image URL
- update test cases
> feat(cameras): add last image URL in camera fetching

- client/pyroclient/client.py
This PR solves #450 by passing down query params from client method
> refactor(client): pass down query param from client
