pyronear/pyro-api

.github/workflows/main.yml, Dockerfile
This PR limits CI triggers to commit and PR on `master` branch. Additionally, fixes the Dockerfile to work as a standalone without docker-compose.
=> chore: Updated CI triggers and refactored Dockerfile

src/app/api/routes/users.py, src/app/api/routing.py, src/app/api/schemas.py, src/tests/test_users.py
This PR adds the possibility of password update by:
- renaming the existing `/update-me` route to `/update-info` for coherence
- adding an admin and personal password update route. Both of them check if the entry exists, then hash the password and updates the entry in the table. For security reasons, instead of returning the input payload, I returned the user name to avoid exposing the password.
- adding corresponding unittests
- refactored schemas by adding a template class `_CreatedAt` and using multi-inheritance to avoid unneeded code duplication
I should bring your attention to route naming: I made the choice mentioned above but perhaps we should clarify the naming of all user routes since it's a complicated table.
=> feat: Added a password update route

src/app/api/schemas.py
This little PR adds default example values to schemas by adding example parameters in classes from schemas.py.
I don't know whether or not to add examples for the fields ids, dates and token. What do you think? 
Also, I am wondering if we should add description to  field. 
Feedbacks are welcome
=> feat: Added default example values to schemas

.github/workflows/main.yml, CONTRIBUTING.md, README.md, docker-compose.yml
This PR reflects changes to the repo name. I wasn't able to update the name of the Heroku deployment since pyro-api.herokuapp.com is already taken.
Any feedback is welcome :ok_hand:
=> refactor: Renamed repo

src/app/api/routes/devices.py
This PR reorders arguments of `update_location` and fixes the value passed to device_id. Previously the value is the built-in `id` function.
=> fix: Fixed the device update location

src/app/db/__init__.py, src/app/db/session.py, src/app/db/tables.py
Following up on suggestions about db initialization in #26, this PR splits table definition and session creation and puts them both in the same module.
The `__init__.py` preserves all imports from other files for ideal compatibility.
=> refactor: Refactored db module

requirements.txt
In #38, tests were failing apparently because of a missing `psycopg2` dependency. So I checked the last previous PR successfully building which is #37:
The build of 37 (https://github.com/pyronear/pyro-api/pull/37/checks?check_run_id=1408361256) installs `databases` v0.4.0 while the other (https://github.com/pyronear/pyro-api/pull/38/checks?check_run_id=1411729940) installs  version 0.4.1. I checked locally and adding an upper bound constraint fixes the issue.
=> fix: Fixed package versioning of databases

src/app/api/routes/media.py
This PR aims at adding summary and description to the media routes.
All routes have a brief summary and brief description
=> [docs][media] Add summary and description to media routes

src/app/api/routes/devices.py, src/app/api/routes/users.py
This PR adjusts the authorized scope of self-ID routes. Initially, admin was not enabled, this fixes it.
=> refactor: Added admin to authorized scopes of selfID routes

src/app/db/init_db.py
Since query filters were recently changed in #37, the db initialization was still using the legacy interface. This PR fixes it
_To prevent this type of issue from happening again, perhaps we should have a github action checking the status of the Heroku deployment upon build completion (pinging the documentation for instance?). I noticed this after trying to access the documentation, and I looked at the logs to find out what was causing the crash_
=> fix: Fixed DB initialization

src/app/api/schemas.py, src/app/db/tables.py, src/tests/test_sites.py
As per #53, this PR adds the "country" and "geocode" fields in the sites table.
- For the "country", I adopted the Alpha-2 ISO convention (https://www.iban.com/country-codes).
- For the "geocode", I'm still searching for a good international convention (perhaps https://en.wikipedia.org/wiki/ISO_3166-2:FR)
This PR will close #53 
=> feat: Added country and geocode fields in the sites table

src/app/api/deps.py
Following the super relevant comment from @florianriche in #45, this PR aims at correcting the authentication behaviour with respect to the scope list.
The list of scopes appears to be an "and" condition, instead of a "or" as we want to design it.
`deps.py` file has been updated to reflect the correct behaviour.
=> [scopes][permissions] update permission condition from "and" to "or" 

src/app/api/routes/installations.py
small error (caught by pyflakes on my machine): timestamp was not defined but belonged to the payload object.
=> fix: get_all_at_given_ts_and_site timestamp call

src/app/api/routes/alerts.py, src/app/api/schemas.py, src/tests/test_alerts.py
As per #63, this PR adds a route for alert acknowledgement. As discussed in the issue, the question of the route scope will be deferred to #45 and not be handled in this PR.
This will close #63 
=> feat: Added a route for alert acknowledgement

src/app/api/routes/accesses.py, src/app/api/routes/alerts.py, src/app/api/routes/devices.py, src/app/api/routes/users.py, src/app/api/schemas.py, src/tests/test_accesses.py, src/tests/test_devices.py, src/tests/test_users.py
When an access/user/device is updated; if the login is in the payload, we check if the updated login doesn't already belong to another user/access/device.
Close #30
=> Check login existence when updating user/access/device

src/app/api/routes/events.py, src/tests/conftest.py
The security of some events routes where decorated with get_current_user with expected scopes ["admin", "device"]. 
But get_urrent_user checks for the access authorization and then that a user exists with the required login. As we were trying to query the route with a device; no such user existed and hence an exception was raised.
In order to make the route works for both admin and device, we replace get_current_user by get_current_access
=> BUGFIX: Events route accesses as device

client/pyroclient/client.py
`Device` instead of `Devices`.
No other error typo observed.
=> 2 chars Bugfix: fix device route location in client

src/app/api/routes/media.py, src/app/services/bucket/baseBucketService.py, src/app/services/bucket/dummyBucketService.py, src/app/services/bucket/qarnotBucketService.py
Upload routes were not working properly with Qarnot:
1. For the upload: Qarnot doesn't accept an int as a bucket key. Had to convert the hash to a string
2. For the image URL retrieval: Qarnot retrieves the bucket objects by downloading them locally and then simply returning the filepath of the object. It seems here is not way to retrieve a public URL. Hence I didn't touch this part, but we have to be aware it is malfunctioning with Qarnot as it will only return the filename (i.e the bucket_key, which is not very useful)
3. For the image retrieval as Bytes: Used to try to read a URL. Now it reads the Bucket File downloaded by Qarnot, uses it in the Response and launch a Background task to delete that file after the route response..
=> fix: Fixed Qarnot image upload and image retrieval

src/app/api/routes/media.py, src/app/api/security.py, src/tests/test_security.py
This PR addresses the naming of bucket file on the CSP by:
- switching from hashing the timestamp to hashing the file content with SHA256
- taking the 32 first characters of the hexadecimal digested string and concatenate it with the file extension
- adding a unittest for the hashing function
=> feat: Upgraded bucket file naming with SHA256

.github/workflows/client-main.yml, .github/workflows/main.yml, src/app/api/routes/media.py, src/app/services/__init__.py, src/app/services/bucket/qarnotBucketService.py, src/app/services/utils.py, src/tests/test_services.py
As witnessed over the past day, we've had some troubles with media upload. Some were fixed in #95 and #96 fortunately, but two issues remained: 
- adding the subfolder in the bucket name was not supported by the CSP client
- empty file could be uploaded, if the byte position of a file were to be offset for instance
This PR fixes both issues by adding a generalized bucket key resolution and resetting the byte position after hashing to avoid uploading empty files. I tried it on my end by deploying the feature branch on Heroku, and it works:
Feel free to try by yourself before the next deployment :ok_hand: 
=> fix: Fixed media content upload to bucket

src/app/api/routes/alerts.py, src/app/api/routes/events.py, src/app/api/routes/installations.py, src/app/api/routes/media.py, src/app/api/routes/sites.py
Following up on #45, I realized I was able to delete all entries in the alerts & media tables without any authentication. So this PR adds admin scope where it's best to start protecting the API.
=> feat: Added admin scopes on tables to protect

src/app/api/routes/alerts.py
Following up on #45, this PR introduces the following modifications:
- added admin scope to alert routes
_We should create an intermediate scope ("supervisor") and self routes ("acknowledge_my_alerts") or have more flexible scope requirements to that only the correct users can interact with a specific alert. But let's keep this for another PR_
=> feat: Added admin scopes to alert routes

src/app/api/routes/media.py, src/tests/routes/test_media.py
Following up on #45, this PR introduces the following modifications:
- renamed the media upload route
- added admin scope to media get and fetch routes
- reindented the table in the media route
_Note: I think there is an issue with our unittests regarding Security/get_current_access. When I test it manually, the changes from this PR do work. But this means that the current unittests should fail (because the default current access doesn't have admin scope). I'll open an issue about this #119_
=> feat: Added proper scopes to media routes

src/app/api/crud/accesses.py, src/app/api/crud/base.py, src/app/api/routes/devices.py, src/tests/routes/test_devices.py
Relates to discussion in #45 (devices route) and closes #103 for the route `PUT /devices/{device_id}/`
* Add admin scope (let's say that only admin can change the `owner_id`)
* Use the option `only_provided` defined in `crud.update_entry` that updates only the fields provided in the payload (eg. the admin only updates the `owner_id`, the device still gets its position, etc.)
* Change low level `payload` argument of crud.base.put to dictionary instead of `pydantic.BaseModel` & migrate routes that used the function
* Add the only_provided option that remove None values from payload, retrieve from table record afterwards to get all fields ? Waiting for feedbacks on this one
This is first iteration, more concret than issue comments haha
=> Align devices update 

src/app/api/schemas.py, src/app/db/tables.py, src/tests/routes/test_installations.py
Following up on #123, this PR introduces the following modifications:
- added a boolean field `is_trustworthy` to the installation (default to True)
- added unittest cases to ensure the default value is True and check payload & response
Resolves #123
=> feat: Added is_trustworthy boolean field to installation table

src/app/api/schemas.py, src/app/db/tables.py, src/tests/routes/test_alerts.py
Following up on #126, this PR introduces the following modifications:
- added a float field `azimuth` to the alert table (default to `None`)
- added unittest cases to ensure default value and value constraints (between 0 and 360), check payload & response
Resolves #126
=> feat: Added azimuth float field to alert table

src/app/api/routes/sites.py, src/app/api/schemas.py, src/app/db/tables.py, src/tests/routes/test_sites.py
Following up on #124, this PR introduces the following modifications:
- added a new site type (still default to `tower`)
- added a new route to create sites that doesn't require admin rights but enforces `type='no_alert'` so that users can create them
- added unittest cases to ensure default value, check payload & response
Resolves #124
=> feat: Added no_alert type to Sites

src/app/api/schemas.py, src/app/db/tables.py, src/tests/conftest.py, src/tests/routes/test_alerts.py, src/tests/routes/test_devices.py, src/tests/routes/test_media.py, src/tests/test_deps.py
Following up on #131, this PR introduces the following modifications:
- added a float field `angle_of_view` to the device table (mandatory in payload)
- added unittest cases to ensure  value constraints (between 0 and 360), check payload & response
- updated other unittests to make it compatible
Resolves #131
=> feat: Added angle_of_view to the device table

scripts/api_e2e.py, src/app/api/crud/accesses.py, src/app/api/routes/login.py, src/app/api/schemas.py, src/app/db/init_db.py, src/app/db/tables.py, src/tests/routes/test_accesses.py, src/tests/routes/test_alerts.py, src/tests/routes/test_devices.py, src/tests/routes/test_events.py, src/tests/routes/test_groups.py, src/tests/routes/test_installations.py, src/tests/routes/test_login.py, src/tests/routes/test_media.py, src/tests/routes/test_sites.py, src/tests/routes/test_users.py, src/tests/test_deps.py
Following up on https://github.com/pyronear/pyro-api/issues/125#issuecomment-803639387 and #137, this PR introduces the following modifications:
- renamed `scopes` field to `scope` in the access table (a given access cannot cumulate more than one now since we removed "me")
- added group_id to the access table
- updated unittests accordingly
=> feat: Added group_id to access table

client/pyroclient/client.py, src/app/api/schemas.py, src/app/db/tables.py, src/tests/routes/test_sites.py
Parts of #137 
This PR ensure that all objects can be linked to a group.
At a first glance, it appears that only site needed some modifications.
Content of the PR:
- Add group_id to site table
- Add group_id to site schema
- Adapted no-alert-site in client
- Adapted UnitTest for site
=> feat: add missing link between site and group

client/pyroclient/client.py, src/app/api/routes/devices.py, src/app/api/schemas.py, src/app/db/tables.py, src/tests/routes/test_alerts.py, src/tests/routes/test_devices.py, src/tests/routes/test_installations.py, src/tests/routes/test_media.py
Following up on #150, this PR introduces the following modifications:
- adds a device route for self GET
- adds a `software_hash` string field to the `devices` table
- adds a route to update the `software_hash` of the current device
- adds corresponding unittests
- adds corresponding client methods
Resolves #150
=> feat: Added software_hash for device update check

client/pyroclient/client.py, src/app/api/schemas.py
Small PR to add the azimuth information in the client messages.
Also add default example values to the Alert Schemas for the software_hash and the azimuth.
=> Client: Add azimuth in alerts functions

client/README.md, src/app/api/routes/alerts.py, src/app/api/routes/devices.py, src/app/api/routes/events.py, src/app/api/routes/installations.py, src/app/api/routes/media.py, src/app/api/routes/sites.py, src/app/api/routes/users.py, src/app/db/__init__.py, src/app/db/models.py, src/app/db/session.py, src/tests/db_utils.py, src/tests/routes/test_alerts.py, src/tests/routes/test_devices.py, src/tests/routes/test_events.py, src/tests/routes/test_groups.py, src/tests/routes/test_installations.py, src/tests/routes/test_media.py, src/tests/routes/test_sites.py, src/tests/routes/test_users.py
Now that we have added SQLAlchemy models, we can now use them to ease the implementation of queries that rely on multiple joins.
Among those queries are the fetching routes that must return results only limited in a specified group_id.
* Add relationships in SQLALchemy models
* Add group_id in standard fetching routes (not yet implemented for all fetching routes)
* Adapted the unit Tests
* Fixed the relationship between events/alerts and the deletion cascading function (previous behavior was buggy.
Can you please check that:
* You agree with this new fetching behavior
* You are fine with the implementation and code organization
* PR to include the group_id logic in the remaining fetching functions
* PR to include the group_id logic in the update functions
=> [groups] Add group logic to fetching routes

client/pyroclient/client.py, client/test/test_client.py
- ensures that headers are refreshed after the token refresh
- extended unittest to make sure that the headers are refreshed
=> fix: Fixed client header refresh

CONTRIBUTING.md, src/app/api/crud/accesses.py, src/app/api/crud/authorizations.py, src/app/api/crud/base.py, src/app/api/crud/groups.py, src/app/api/deps.py, src/app/api/routes/alerts.py, src/app/api/routes/devices.py, src/app/api/routes/events.py, src/app/api/routes/groups.py, src/app/api/routes/installations.py, src/app/api/routes/login.py, src/app/api/routes/media.py, src/app/api/routes/sites.py, src/app/api/routes/users.py, src/app/api/routes/webhooks.py, src/tests/routes/test_accesses.py, src/tests/routes/test_alerts.py, src/tests/routes/test_devices.py, src/tests/routes/test_events.py, src/tests/routes/test_groups.py, src/tests/routes/test_installations.py, src/tests/routes/test_login.py, src/tests/routes/test_media.py, src/tests/routes/test_sites.py, src/tests/routes/test_users.py
Following up on #161, this PR introduces the following modifications:
- fixes the instruction to run the unittest in CONTRIBUTING
- Specified error codes (cf. https://kinsta.com/blog/http-status-codes/): 404 when an entry isn't found, 401 when token expires or creds aren't valid, 409 when there is a conflict, 403 when the authorization level doesn't allow an operation
- Added detailed error messages for each `HTTPException`
- updated unittest accordingly
Closes #161 
=> feat: Specified HTTP status code and error messages

client/test/test_client.py, mypy.ini, src/app/api/schemas.py, src/requirements-dev.txt
The azimuth was wrongly constrained between -180 and +180, while it should have been 0 and 360.
This PR fixes that, pinned the `httpx` version which caused problems during testing, and I fixed the client unittests which were failing on a very rare edge case
=> refactor: Moved azimuth angle from (-180, +180) to (0, 360)

src/app/api/crud/alerts.py, src/app/api/crud/base.py, src/app/api/routes/alerts.py, src/tests/routes/test_groups.py
- added a configurable limit to the size of the return response (set to 50 for now)
- adds a dedicated test case
For table with large number of entries, this will considerably speed it up. This PR makes it so that the limit is embedded in the SQL request (not done a posteriori).
That should help a lot with ongoing_alerts @Akilditu !
=> feat: Added max request response size for fetch routes

.github/workflows/builds.yml, .github/workflows/style.yml
This PR simply fixes the cache key for env restoration and optimized secondary keys. The result should be a speed up on PRs with multiple CI runs.
=> ci: Optimized CI cache

.github/dependabot.yml
This PR removes the version update of the dependabot (alerts and security updates will still work)
=> ci: Removed version update for dependabot

poetry.lock, pyproject.toml, src/app/api/routes/media.py, src/app/requirements.txt, src/requirements-dev.txt, src/tests/routes/test_media.py
- updates bucket name resolution: formerly hash first 32 characters + ".file", now timestamp + fash first 8 characters + extension (using mimetype guessing)
- delete the previous file from bucket when a media is assigned a new file via upload
- deletes file when media is deleted
- updates test accordingly
Closes #94
=> fix: Fixed media duplication

client/README.md
This PR simply fixes the URL of the documentation in the client README.
=> docs: Fixes URL of client documentation

client/.conda/meta.yaml
This PR fixes the URL of the conda recipe
=> chore: Fixed URL in conda recipe

.github/workflows/main.yml, Makefile, docker-compose-dev.yml, docker-compose.yml, nginx/nginx.conf, pyproject.toml, src/app/api/routes/media.py, src/app/api/security.py, src/app/config.py, src/app/services/bucket/__init__.py, src/app/services/bucket/qarnot.py, src/app/services/bucket/s3.py, src/tests/routes/test_media.py
This PR adds support for alternative S3 storage interfaces, and refactors QarnotBucket as an S3Bucket. Additionally, this PR improves the media upload route:
- previously, we uploaded the file, then downloaded it to check that the hash is identical (1 upload + 1 download)
- with this PR, we upload the file, then only read the MD5 hash computed by S3 file system (1 upload)
This should speed up the route while decreasing bandwidth requirements.
=> feat: Added support of alternative S3 storage

client/pyroclient/client.py
This PR fixes #219 where the client modification wasn't made to align with the new table column naming.
=> fix: Fixed arg naming for location updating

.pre-commit-config.yaml, client/pyroclient/client.py, client/tests/conftest.py, client/tests/test_client.py, client/tests/test_exceptions.py, src/app/api/endpoints/alerts.py
- adds extensive tests for the client
- fixes a rare case on the alert endpoint (when azimuth is not specified, it defaults to the value of the device that created the alert, but if for some reason, the device azimuth is None, that creates an internal error)
- deprecates the following client methods: `update_my_location`, `create_event`, `create_no_alert_site`, `send_alert`, `create_media`, `get_media_url_and_read`
- renamed the following client methods: `get_my_devices` --> `get_user_devices`, `get_my_device` -> `get_self_device`
- updates precommit hooks
Closes #224
=> test: Adds extensive test for the client and fixed alert endpoint

.github/workflows/scripts.yml
I noticed, the CI job for E2E script wasn't running anymore. This needs to be addressed so here it is!
=> ci: Makes script job independent form tests

src/app/api/endpoints/media.py
This PR ensures that we only try to remove a bucket file if the media has one that was set. I tested on my environment, this PR fixes the script issues in #245.
Closes #259
=> fix: Fixes media deletion route by checking bucket file existence

.github/workflows/style.yml, client/pyproject.toml, pyproject.toml, src/app/schemas/base.py, src/app/schemas/devices.py, src/app/schemas/events.py, src/app/schemas/installations.py, src/tests/routes/test_installations.py
This PR handles the tedious datetime & timezone issues by sanitizing all of them:
- removes tzinfo from datetime when relevant
- parses datetime information that have "Z"
- specifies swagger examples to avoid Z (which indicate UTC timezone --> we want ISO format independent on TZ, thus UTC, but as a convention and not being specifying UTC as if we could pass UTC+2)
- adds test cases
- updates version specifiers of the API & client
Closes #261
=> fix: Fixes the parsing of datetime

docker-compose.yml, src/app/api/endpoints/media.py
- fixes the access check on media URL resolution. Interesting fact about why this wasn't spotted earlier: we were using the user ID as access ID, which is not a problem when you create all the users before any device (because then access ID = user ID). Hence the problem @MateoLostanlen (I got the idea because I didn't encounter the problem when using the superadmin which is the first access that gets created, but had the problem with other admins, where the user ID != access ID)
- avoids DB direct exposition for external HTTP requests
=> fix: Fixes access ID resolution on media URL resolution

src/app/config.py
This PR allows the docker compose to specify the secret key as env parameters. The nice part is that this prevents the expiration of tokens when restarting the container (thus heartbeat won't expire all the time).
=> feat: Adds possibility to specify secret key

src/app/api/crud/alerts.py, src/app/config.py
When a device issues multiple alerts, it is associated to an existing event if it is within "relaxation time". This PR increases the relaxation time from 5 to 30 minutes to avoid creating multiple events for the same fire detection. The risk to miss another fire within the relaxation time is considered small at this point.
=> refactor: change alert relaxation from 5 to 30 minutes

src/app/services/bucket/s3.py
The endpoint_url reference in the method to generate file download URL is missing. This PR fixes that
=> fix: Adds missing reference to the endpoint_url for the S3 proxy

.github/labeler.yml, .github/workflows/tests.yml, .gitignore, Makefile, docker-compose.test.yml, src/app/config.py, src/tests/conftest.py, src/tests/db_utils.py
This PR simplifies the testing procedure by:
- removing the volume binding for the docker orchestration of test (making sure we don't alter local prod database, and no point keeping test data)
- removing the test_db to instead clear & populate the main database. Because it's now unbinded, the volume is fresh on each test procedure and doesn't affect the potential local volume that holds the database
The advantage is that it reduces the number of docker containers to handle, and removes some config variables.
Additionally, "docker-compose-dev.yml" was renamed to "docker-compose.test.yml" to reflect common practices.
=> test: Simplifies testing procedure by using unbinded Docker

.github/workflows/builds.yml, .github/workflows/scripts.yml, .github/workflows/tests.yml, CONTRIBUTING.md, Makefile, README.md, docker-compose.test.yml, docker-compose.yml, scripts/api_e2e.py, scripts/pg_extract.sh, src/app/api/endpoints/alerts.py
- updates to postgres 15 to avoid upcoming deprecation (and it happens to be faster)
- fixes a minor issue with alert ordering (seems like this didn't happen on PG 12)
- switches to new docker syntax (docker-compose --> docker compose)
- moves prod env var to .env
- adds health checks in the docker compose
To upgrade existing DB, I tried locally, you just need to:
on the PG 12.1 (dump only the data, removing the PG version specific aspects, then delete the volume)
```shell
docker compose exec -it db pg_dumpall -U mybdsuperuserpyro > my_local_dump.sql
./scripts/pg_extract.sh my_local_dump.sql pyro_api_prod >> upgrade_dump.sql
docker compose down
docker volume rm pyro-api_postgres_data
```
On the PG 15 (we only run the db so that it stays …
=> chore: Bumps PG version to 15 to avoid deprecation

README.md, poetry.lock, pyproject.toml, src/app/api/crud/alerts.py, src/app/api/endpoints/alerts.py, src/app/api/endpoints/devices.py, src/app/api/endpoints/events.py, src/app/api/endpoints/installations.py, src/app/api/endpoints/media.py, src/app/api/endpoints/notifications.py, src/app/api/endpoints/sites.py, src/app/api/endpoints/users.py, src/app/config.py, src/app/services/__init__.py, src/app/services/bucket/__init__.py, src/app/services/services.py, src/app/services/storage.py, src/app/services/telemetry.py, src/tests/routes/test_media.py, src/tests/test_services.py
- simplifies the storage interactions (bucket/s3 --> storage.py)
- adds a telemetry client
- adds event capture on most routes
cf. #304
=> feat: Adds product analytics on most of the routes

src/app/api/endpoints/devices.py
This PR modifies the feature introduced in #307 for product analytics by disabling tracking of the most frequent signal (heartbeat). There are too many not to hit the free quota limit (we get more than 1/sec)
=> fix(apm): Disable posthog events when there is a heartbeat

.github/workflows/scripts.yml, .github/workflows/tests.yml, client/pyroclient/client.py, client/tests/conftest.py, scripts/api_e2e.py, src/Dockerfile, src/Dockerfile-dev, src/app/api/endpoints/accesses.py, src/app/api/endpoints/alerts.py, src/app/api/endpoints/devices.py, src/app/api/endpoints/events.py, src/app/api/endpoints/groups.py, src/app/api/endpoints/installations.py, src/app/api/endpoints/login.py, src/app/api/endpoints/media.py, src/app/api/endpoints/notifications.py, src/app/api/endpoints/recipients.py, src/app/api/endpoints/sites.py, src/app/api/endpoints/users.py, src/app/api/endpoints/webhooks.py
- reflects the final slash in the endpoint of base router (cf. https://github.com/pyronear/pyro-api/blob/main/src/app/api/endpoints/sites.py#L22) by modifying the client routes
- make sure the API is redirecting to the trailing slash endpoint in the backend to avoid problems later
- add a test case in the integration test script
- speeds up the dependencies installation in the Docker images
cc @MateoLostanlen
=> fix(client): handle the final slash sensitivity on core routers

poetry.lock, pyproject.toml
This PR bumps requests from 2.31.0 to 2.32.0 and idna from 3.4 to 3.7.
cf. https://github.com/pyronear/pyro-api/security/dependabot/41
cf. https://github.com/pyronear/pyro-api/security/dependabot/38
=> build(deps): bump requests & idna to security compliant versions

poetry.lock
This PR bumps urllib3 from 1.26.18 to 1.26.19
cf. https://github.com/pyronear/pyro-api/security/dependabot/42
=> build(deps): bump urllib3 from 1.26.18 to 1.26.19

src/app/api/api_v1/endpoints/detections.py, src/app/services/storage.py
If you are connected as an admin, the bucket par defaut is "admin" but the endpoint Detection was using the "alert-api-1" name.
Anyway we should not use any of this two solutions when requesting for an URL, we need to use the Detection_id instead
=> Fix :the admin behavior for bucket requests

.github/workflows/push.yml
This PR fixes a small problem introduced in #322 as the CI workflow job was renamed but the depending job didn't update the reference to it. This will now push again the latest version of the docker image to Dockerhub & GitHub container registry
=> ci(push): fix workflow syntax for push job

poetry.lock, pyproject.toml
This PR bumps a few packages to resolve the security alerts from dependabot
=> build(deps): bump certify, multipart, sentry & setuptools

.github/labeler.yml, CONTRIBUTING.md, scripts/dbdiagram.txt, src/app/api/api_v1/endpoints/detections.py, src/app/api/api_v1/endpoints/webhooks.py, src/app/api/api_v1/router.py, src/app/api/dependencies.py, src/app/crud/__init__.py, src/app/crud/crud_webhook.py, src/app/models.py, src/app/schemas/__init__.py, src/app/schemas/webhooks.py, src/tests/conftest.py, src/tests/endpoints/test_webhooks.py
This PR adds a small webhook table, and used when detection are created as background tasks. I made webhooks editable only by admins, and they post the detection payload for now. We'll be able to edit what gets sent upon dispatch later if needed
Here is the new UML:
=> feat(webhooks): add webhook mechanism on detection creation

CONTRIBUTING.md, client/pyroclient/client.py, client/tests/test_client.py, pyproject.toml, scripts/dbdiagram.txt, src/app/api/api_v1/endpoints/cameras.py, src/app/api/api_v1/endpoints/detections.py, src/app/models.py, src/app/schemas/cameras.py, src/app/services/storage.py, src/tests/conftest.py, src/tests/endpoints/test_cameras.py
- add a "last_image" column in the Camera table
- every time a camera uses it, it uploads an image, stores it in the bucket (and delete the previous one) + update the DB entry
- update the client & corresponding tests
- update the UML & made it live
Here is the updated UML
(live link: https://dbdiagram.io/d/Pyronear-UML-665a15d0b65d933879357b58)
=> feat(cameras): add a route to update the last known image of a camera

.env.example, CONTRIBUTING.md, poetry.lock, pyproject.toml, scripts/dbdiagram.txt, src/app/api/api_v1/endpoints/detections.py, src/app/api/api_v1/endpoints/organizations.py, src/app/core/config.py, src/app/crud/crud_organization.py, src/app/models.py, src/app/schemas/organizations.py, src/app/services/telegram.py, src/tests/conftest.py, src/tests/endpoints/test_organizations.py, src/tests/services/test_telegram.py
This PR is greatly inspired from #272 by @blenzi 🙏 
It introduces the following modifications:
- add Telegram as a service + test cases (verifying token, channel access, etc.)
- add the possibility for each org to have a dedicated telegram channel ID (created by human admins, where the bot has to be invited)
- when a detection is created, on top of webhooks, we send the detection payload to the channel (unformatted for now)
Here is the updated DB schema: https://dbdiagram.io/d/Pyronear-DB-671e1b9897a66db9a3673d76
cc @MateoLostanlen
=> feat(organizations): add optional Telegram notifications for detections

src/app/api/api_v1/endpoints/detections.py, src/app/crud/base.py
When calling the fetch unlabeled detections endpoint with an ADMIN token, the pictures were not found in the S3 because the organisation_id of ADMIN is = 1, while we would like to get all the Detection of all the organization.
So for ADMIN token we should find the organization_id thanks to the Camera.detection_id
=> Fix fetch unlabeled detections endpoint

README.md
This PR updates the docker badge from legacy reference to new images.
=> docs(readme): fix the dockerhub ref in badge

.github/workflows/builds.yml, .github/workflows/docs.yml, .github/workflows/publish.yml, .github/workflows/pull_requests.yml, .github/workflows/push.yml, .github/workflows/scripts.yml, .github/workflows/style.yml, .github/workflows/tests.yml, .pre-commit-config.yaml, poetry.lock, pyproject.toml, src/Dockerfile
- update Dockerfile and CI to use python3.11 (faster execution)
- use uv instead of pip everywhere it's possible (dependency installation is considerably faster with that)
- use env variable for easier CI workflow version bump
=> build(docker): update CI and docker to pythono 3.11 using uv

src/app/api/api_v1/endpoints/detections.py, src/app/schemas/detections.py, src/tests/endpoints/test_detections.py
I couldn't rebase properly #399 so I went minimal with this one. This updates the lower bound constraint on azimuth value and add a test case
close #395
=> fix(detections): allow azimuth=0 for the detection table

src/app/api/api_v1/endpoints/detections.py
As mentioned in #413, I think the webhook trigger and Telegram notifications should only be considered when a sequence is created (several detections in a row from the same camera and azimuth) vs. when a detection is created (more prone to false positives and noise).
This PR moves both to sequence creation
=> feat(detections): restrict webhook and telegram to sequence creation

src/app/api/api_v1/endpoints/cameras.py, src/app/api/api_v1/endpoints/detections.py
This PR enforces ordering by ID for fetch commands. This changes the order on the camera fetching and detection fetching routes
Close #425
=> refactor(api): enforce fetch results to be ordered by ID

src/app/api/api_v1/endpoints/sequences.py
Hi there, 
Small suggestion for the summary of the endpoint `sequences/unlabeled/latest`. 
The actual summary is a bit ambiguous to me as the term `unlabeled` does not appear (albeit it is present in the endpoint name) & there is no explanation of what is meant by `latest`
Hence, this small PR introduces a more explicit formulation : "Fetch all the unlabeled sequences from the last 24 hours".
If we do not want to explicit latest, this formulation could be ok : "Fetch all the latest unlabeled sequences"
What do you think ? 
Happy to discuss it !
=> docs: Updated sequences/unlabeled/latest endpoint summary

src/app/api/api_v1/endpoints/cameras.py, src/app/crud/crud_camera.py, src/app/schemas/cameras.py, src/tests/endpoints/test_cameras.py
This PR adds `PATCH /cameras/{cam_id}/location` route to edit the lat, lon and elevation of a camera, along with test cases. Please note this isn't adding a client route on purpose, as this is only meant to be used by admins for now
Closes #447
=> feat(cameras): add PATCH route to edit camera location

client/pyroclient/client.py, scripts/test_e2e.py, src/app/api/api_v1/endpoints/sequences.py
This PR adds new params to the backend endpoint `GET /api/v1/sequences/{sequence_id}/detections` and the corresponding client method:
- limit: change the maximum number of items returned (default 10, min 1, max 100)
- desc: boolean flag specifying whether the result should be ordered by decreasing creation date (default = True)
=> feat(sequences): add limit and desc params in fetch_sequence_detections
